### ISSUE TITLE
let / fn, recursively

### ISSUE THREAD

**Issue by taiyakihitotsu** [taiyakihitotsu/lots#12]
two or more syms / args pattern are able to implement easily when it will have done.

## Test Cases
1. [x] fn in fn #24 
2. [x] let in let #24
3. [x] fn in let #27 
4. [x] let in fn #27

And the case if arg names would be the same.
